import { Poppins } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/shared/theme/theme-provider"
import { Toaster } from "@/components/ui/toaster"

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <ThemeProvider attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange>
    <ClerkProvider>
      <body className={poppins.className}>{children}</body>
      <Toaster />
      </ClerkProvider>
      </ThemeProvider>
    </html>
  )
}
